### ISSUE TITLE
Sublime Text 3 Support -  Error: Cannot find module

### ISSUE THREAD

**Issue by nodesocket** [73rhodes/Sublime-JSLint#13]
Just installed JSLint on **Sublime Text 3** with the package manager, but getting:

```
Error: Cannot find module '/Users/justin/Library/Application Support/Sublime Text 3/Packages/JSLint/linter.js'
```

Does JSLint work with Sublime Text 3?

**Comment by wuchun4** [comment]
No matching processes belonging to you were found
module.js:329
    throw err;
    ^

Error: Cannot find module '/Volumes/Macintosh'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3

**Comment by HuanChu369** [comment]
`cd /Users/H/Library/Application\ Support/Sublime\ Text\ 2/Packages/User`

Maybe you can try this one, use '\ ' replace all of space in the command .
