### ISSUE TITLE
 Update version of JSLint

### ISSUE THREAD

**Issue by dsernst** [73rhodes/Sublime-JSLint#41]
The `jslint.js` that currently comes with this package is from `2013-08-26`. Do you have plans to update this? Especially in light of the "new" JSLint released in the last few months.

**Comment by dsernst** [comment]
There have been about ~50 commits https://github.com/douglascrockford/JSLint/commits/master/jslint.js since https://github.com/douglascrockford/JSLint/commit/650bcde1642e53cbfbd248a6092ddebb61ce3985#diff-01d3d81a6eb6d82af3c377b55dc4fa28

**Comment by dsernst** [comment]
Simply replacing the `jslint.js` this package comes with the new version results in:

```
/Users/dsernst/Library/Application Support/Sublime Text 3/Packages/JSLint/linter.js:41
    var success = JSLINT(data, options),
                  ^
TypeError: object is not a function
    at /Users/dsernst/Library/Application Support/Sublime Text 3/Packages/JSLint/linter.js:41:19
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
[Finished in 0.1s with exit code 1]
```

**Comment by dsernst** [comment]
Yes no maybe?

**Comment by 73rhodes** [comment]
:+1:

**Comment by dsernst** [comment]
:sweet_potato:
