### ISSUE TITLE
How to config indent size?

### ISSUE THREAD

**Issue by hoangnguyencong** [73rhodes/Sublime-JSLint#47]

**Comment by jklepp-tgm** [comment]
You can put a config file called ``.jslintrc`` into your home directory.
``` json
{
    "indent": 2
}
```

For some reason the JSLint version shipped with this plugin ignore the config file so you have to use your own version of JSLint and you also will have to change the jslint command in the plugin settings.

A different approach is to put a comment like ``/*jslint indent: 2*/`` into your js files.

**Comment by MarcosRava** [comment]
#1 Bad option 'indent'.
    /*jslint node: true, indent: 2 */ // Line 1, Pos 1
 #2 Unexpected expression 'use strict' in statement position.
    "use strict"; // Line 2, Pos 1

**Comment by 73rhodes** [comment]
JSLint no longer supports an option for indentation. Please log an issue against JSLint to request that this option be reinstated. Note that Sublime-JSLint allows you to use any version of JSLint you want to. Just change your config settings to point to it on your file system.

**Comment by donnykurnia** [comment]
The 2015-10-08 jslint.js now hardcoded 4 margin and no longer accept indent option.

**Comment by 73rhodes** [comment]
https://github.com/douglascrockford/JSLint/commit/f819cf3c65d07086cf217c549c577fa77dc65fc9#commitcomment-14603692

**Comment by hoangnguyencong** [comment]
@jklepp-tgm, @MarcosRava ,@donnykurnia, @73rhodes thank for your feedbacks :+1:
