### ISSUE TITLE
[Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by dheeraja00** [73rhodes/Sublime-JSLint#5]
I have installed JSlint as per mentioned steps but when I tried to run it I got below error:

[Error 2] The system cannot find the file specified
[cmd:  [u'/usr/local/bin/node', u'/usr/local/bin/jslint', u'--sloppy', u'--indent', u'2', u'--node', u'--nomen', u'--vars', u'--plusplus', u'--stupid', u'']]
[dir:  C:\Users\agrawal_d\AppData\Roaming\Sublime Text 2\Packages]
[path: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;c:\Python27;C:\Program Files\nodejs\;C:\Users\agrawal_d\AppData\Roaming\npm]
[Finished]

**Comment by arvind07** [comment]
It seems weird but in my case the solution is different. I was getting following error:
`FileNotFoundError: [WinError 3] The system cannot find the path specified: 'c:\\users\\arvind~1\\appdata\\local\\temp\\SublimeLinter3-arvind\\app.js'
 `

I checked the `c:\\users\\arvind~1\\appdata\\local\\temp\\` folder and found that it had not `SublimeLinter3-arvind` folder. I created this folder manually and JSHint it started working..
