### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by aml2326** [73rhodes/Sublime-JSLint#8]
Maybe it's something I'm doing wrong or something that changed on my system that's caused my error but It was working at one point and now its not. 

I've upgrade node js to v0.10.1, confirmed in terminal by runinng node --version. If I run jslint in terminal it spits out an error saying "No files specified." so I know thats installed as well. I've tried removing the jslint package from sublime and reinstalling a few times just to see if that would fix it be every time I receive the "[Errno 2] No such file or directory" error when saving a JS file. Any thoughts as to how to fix this error?

[Errno 2] No such file or directory
[cmd:  [u'node', u'/Users/Adam Leder/Library/Application Support/Sublime Text 2/Packages/JSLint/linter.js', u'--sloppy', u'--indent', u'2', u'--node', u'--nomen', u'--vars', u'--plusplus', u'--stupid', u'--todo', u'/private/var/www/mad-athlete/public_html/assets/js/script.js']]
[dir:  /private/var/www/mad-athlete/public_html/assets/js]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

It also seems like 'u' is being prepended in front of all the strings for the [cmd:]

Thanks for your help!

**Comment by sfbayman** [comment]
@darrenderidder  your solution worked for me. Thanks.
